example.property: I AM MASTER

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ostock_dev
    username: root
    password: root

spring.sql.init.mode: always

spring.jpa.hibernate.ddl-auto: update